title: HoneyHive Newsletter
description: Daily tech news curated by HoneyHive
url: "https://blog.honeybarrel.co.kr"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Feed
feed:
  path: feed.xml

# Collections
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Exclude
exclude:
  - README.md
  - LICENSE
